### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by benofben** [benofben/arbit#14]
I got some sort of network error, but didn't keep the bug.  Will try to catch it next time.

**Comment by benofben** [comment]
Here we go:

Traceback (most recent call last):
  File "downloaderQuotes.py", line 35, in <module>
    downloader()
  File "downloaderQuotes.py", line 14, in __init__
    self.schedule.run()
  File "/usr/lib/python3.4/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "downloaderQuotes.py", line 19, in download
    quotes.downloader.run()
  File "/home/benton_lackey/arbit/downloader/quotes/downloader.py", line 14, in run
    upload()
  File "/home/benton_lackey/arbit/downloader/quotes/downloader.py", line 104, in upload
    db.upload(constants.dataDirectory + 'quotes.csv')
  File "/home/benton_lackey/arbit/downloader/quotes/database.py", line 36, in upload
    self.table.upload_from_file(readable, source_format='CSV', skip_leading_rows=0)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/bigquery/table.py", line 969, in upload_from_file
    http_response = upload.stream_file(use_chunks=True)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/streaming/transfer.py", line 1094, in stream_file
    response = send_func(self.stream.tell())
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/streaming/transfer.py", line 1223, in _send_chunk
    return self._send_media_request(request, end)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/streaming/transfer.py", line 1133, in _send_media_request
    self.bytes_http, request, retries=self.num_retries)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/streaming/http_wrapper.py", line 384, in make_api_request
    redirections=redirections)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/streaming/http_wrapper.py", line 347, in _make_api_request_no_retry
    redirections=redirections, connection_type=connection_type)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/transport.py", line 169, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python3.4/dist-packages/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python3.4/dist-packages/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.4/dist-packages/httplib2/__init__.py", line 1017, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

**Comment by benofben** [comment]
Oh sigh...  this is the BigQuery client crapping itself here:
self.table.upload_from_file(readable, source_format='CSV', skip_leading_rows=0)

I'm significantly less enamored of BigQuery now.  I wonder what is going wrong...

Gah.  Googling the error I see: http://stackoverflow.com/questions/16326222/unable-to-load-data-into-bigquery-badstatusline (basically load it to a bucket first)

It's a bit tempting to give Athena a go to compare, but I'm concerned that will just move everything from load time errors to analysis time errors.  I'm still laboring under the assumption that if I can get this all into some ecosystem than life will be easier than my bespoke mongo/PHP/d3 stuff I put together previously.  That could be a mistaken assumption.

It looks like the quotes.csv I'm dumping is 815m.  I believe that's a few years of data, though if I recall Yahoo goes back 10 years or so if you don't limit it.  I could add some code to do the bucket copy.  It seems like a deal breaker if I need that for EDGAR too.  I'm going to think about this for a bit.

**Comment by benofben** [comment]
...there's an additional advantage of going with the AWS stack --- I might be able to refactor all this to use Lambda.  App Engine doesn't support python 3 yet and I don't think I can stomach going back to 2 after all this time.

**Comment by benofben** [comment]
Err.  Looks like Lambda doesn't support python 3 yet either.  Serverless is not the magic fairy land I was hoping it was going to be...

**Comment by benofben** [comment]
...back to the original issue.  I can't find anything explaining why the BigQuery call failed.  I may send a note to Kevin or someone.

It's probably going to be fast to go down the apparently more well adopted path of copying to a bucket.  I don't think I can face doing that right now so I'm going for a walk and I'll think about it...

**Comment by benofben** [comment]
Still no response.  I'm going to retest this and see if they fixed it.  I'll need to figure out how to update the drivers on my VM.  I'm also going to look at wrapping this in a try/catch and retry to see if it's a constant bug.

**Comment by benofben** [comment]
If you wait long enough, everything changes.... It looks like the Yahoo Finance API is different now (10 years later...) https://query1.finance.yahoo.com/v7/finance/download/ORCL?period1=1540332617&period2=1543014617&interval=1d&events=history&crumb=1EKnpl1YcAv

**Comment by benofben** [comment]
Yeah, no:
![image](https://user-images.githubusercontent.com/8282917/48962423-a75c9300-ef34-11e8-8406-a84cac811b91.png)

**Comment by benofben** [comment]
I seem to have fixed this by moving to some new Yahoo thing.
