### ISSUE TITLE
EDGAR - 65 connections exceeded

### ISSUE THREAD

**Issue by benofben** [benofben/arbit#2]
EDGAR apparently only allows 65 concurrent connections.  That causes an uncaught exception.

I am going to email a summary of insider trades for 2016-07-19.
Done with EDGAR download at 2016-07-19T22:49:18.826878
Going to run EDGAR download next at 2016-07-20T22:30:00
Running EDGAR download at 2016-07-20T22:30:00.099139
Traceback (most recent call last):
  File "downloaderEDGAR.py", line 41, in <module>
    downloader()
  File "downloaderEDGAR.py", line 20, in **init**
    self.schedule.run()
  File "/usr/local/lib/python3.4/sched.py", line 151, in run
    action(_argument, *_kwargs)
  File "downloaderEDGAR.py", line 24, in download
    edgar.downloader.run()
  File "/home/ec2-user/arbit/edgar/downloader.py", line 12, in run
    ftp.login()
  File "/usr/local/lib/python3.4/ftplib.py", line 419, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "/usr/local/lib/python3.4/ftplib.py", line 272, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.4/ftplib.py", line 245, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Sorry, the maximum number of allowed clients (65) are already connected.

**Comment by benofben** [comment]
Just got another one of these.  This is apparently my punishment for depending on a server the government runs...

**Comment by benofben** [comment]
I did a pretty major refactor of the code.  Here's where this is currently failing:

benton_lackey@downloader:~/arbit/downloader$ python3 downloaderEDGAR.py 
Going to run EDGAR download next at 2016-11-27T22:30:00
Running EDGAR download at 2016-11-27T23:15:56.082400
Traceback (most recent call last):
  File "downloaderEDGAR.py", line 41, in <module>
    downloader()
  File "downloaderEDGAR.py", line 20, in __init__
    self.schedule.run()
  File "/usr/lib/python3.4/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "downloaderEDGAR.py", line 24, in download
    edgar.downloader.run()
  File "/home/benton_lackey/arbit/downloader/edgar/downloader.py", line 12, in run
    ftp.login()
  File "/usr/lib/python3.4/ftplib.py", line 419, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "/usr/lib/python3.4/ftplib.py", line 272, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.4/ftplib.py", line 245, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Sorry, the maximum number of allowed clients (65) are already connected.

**Comment by benofben** [comment]
Doesn't matter since everything is http now.
