### ISSUE TITLE
Quotes - fails on GCP project issue

### ISSUE THREAD

**Issue by benofben** [benofben/arbit#21]
I wonder if it forgets what project it's part of from being long running?  Though maybe that doesn't make sense because the symbols seem to be working.

Regardless, I probably need to fix the quota limits first.

Reformating the quotes...
Done reformating quotes
Writing quotes to the database...
Done uploading quotes to the database
Done with quotes download at 2016-12-15T01:02:45.868283
Going to run quotes download next at 2016-12-16T00:30:00
Running quotes download at 2016-12-16T00:30:00.100182
Traceback (most recent call last):
  File "downloaderQuotes.py", line 35, in <module>
    downloader()
  File "downloaderQuotes.py", line 14, in __init__
    self.schedule.run()
  File "/usr/lib/python3.4/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "downloaderQuotes.py", line 19, in download
    quotes.downloader.run()
  File "/home/benton_lackey/arbit/downloader/quotes/downloader.py", line 12, in run
    download()
  File "/home/benton_lackey/arbit/downloader/quotes/downloader.py", line 24, in download
    db = symbols.database.database()
  File "/home/benton_lackey/arbit/downloader/symbols/database.py", line 10, in __init__
    self.client = bigquery.Client()
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/client.py", line 185, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/usr/local/lib/python3.4/dist-packages/google/cloud/client.py", line 143, in __init__
    raise EnvironmentError('Project was not passed and could not be '
OSError: Project was not passed and could not be determined from the environment.

**Comment by benofben** [comment]
Moved to AWS so oh well.....
