### ISSUE TITLE
EDGAR - Fail to download file

### ISSUE THREAD

**Issue by benofben** [benofben/arbit#22]
This is strange because it's probably referenced in the master file:

Parsing Form 4 file /home/benton_lackey/arbit_data/edgar/data/1216700/0001209191-16-145081.txt
Traceback (most recent call last):
  File "/home/benton_lackey/arbit/downloader/edgar/downloader.py", line 143, in downloadForm4File
    ftp.retrbinary('RETR ' + filename, open(downloadFilename, 'wb').write)
  File "/usr/lib/python3.4/ftplib.py", line 441, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/lib/python3.4/ftplib.py", line 398, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib/python3.4/ftplib.py", line 364, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/lib/python3.4/ftplib.py", line 272, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.4/ftplib.py", line 245, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 edgar/data/1216700/0001493152-16-013869.txt: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "downloaderEDGAR.py", line 41, in <module>
    downloader()
  File "downloaderEDGAR.py", line 20, in __init__
    self.schedule.run()
  File "/usr/lib/python3.4/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "downloaderEDGAR.py", line 24, in download
    edgar.downloader.run()
  File "/home/benton_lackey/arbit/downloader/edgar/downloader.py", line 31, in run
    downloadForm4File(ftp, form4Filename)
  File "/home/benton_lackey/arbit/downloader/edgar/downloader.py", line 146, in downloadForm4File
    raise Exception('Failed to download form 4 file ' + filename)
Exception: Failed to download form 4 file edgar/data/1216700/0001493152-16-013869.txt
benton_lackey@downloader:~/arbit/downloader$

**Comment by benofben** [comment]
Doesn't matter since everything is http now.
