### ISSUE TITLE
EDGAR 503

### ISSUE THREAD

**Issue by benofben** [benofben/arbit#23]
We have 1787 Form 4 URLs for the date 2018-11-02
Traceback (most recent call last):
  File "downloadAll.py", line 12, in <module>
    run()
  File "downloadAll.py", line 10, in run
    edgar.downloadDate(date)
  File "/home/benton_lackey/arbit/downloader/edgar/edgar.py", line 47, in downloadDate
    transactions = form4.download(url)
  File "/home/benton_lackey/arbit/downloader/edgar/form4.py", line 119, in download
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

**Comment by benofben** [comment]
Maybe fixed by https://github.com/benofben/arbit/commit/6a2ed5061a6b925b1e07d91c8055107a84ad9aa9

**Comment by benofben** [comment]
Errr hmmm.  Now I'm just getting a bunch of forbidden.  Need to figure out what url that is.

**Comment by benofben** [comment]
Moving EDGAR out of scope....
